import React, { useState } from 'react';
import { OrganizationUser } from '../types';
import { validateEmail, validateUserName, generateAccessCode, sendWelcomeEmail } from '../utils/userUtils';

interface UserCreationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreateUser: (userData: Partial<OrganizationUser>) => Promise<void>;
  organizationId: string;
}

const UserCreationModal: React.FC<UserCreationModalProps> = ({
  isOpen,
  onClose,
  onCreateUser,
  organizationId
}) => {
  const [userData, setUserData] = useState({
    name: '',
    email: '',
    role: 'enumerator' as 'admin' | 'project_manager' | 'enumerator' | 'supervisor'
  });
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      await onCreateUser({
        organization_id: organizationId,
        user_id: `user_${Date.now()}`, // Placeholder, use real user ID in production
        name: userData.name,
        email: userData.email,
        role: userData.role,
        access_code: '', // Generated by backend
        is_active: true,
      });
      onClose();
      setUserData({ name: '', email: '', role: 'enumerator' });
    } catch (err) {
      setError('Erreur lors de la création de l\'utilisateur');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-md">
        <h2 className="text-xl font-bold mb-4">Créer un Nouvel Utilisateur</h2>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Nom de l'utilisateur
            </label>
            <input
              type="text"
              value={userData.name}
              onChange={(e) => setUserData({ ...userData, name: e.target.value })}
              required
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md dark:bg-gray-700 dark:text-white"
              placeholder="Ex: Marie Dupont"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Email (optionnel)
            </label>
            <input
              type="email"
              value={userData.email}
              onChange={(e) => setUserData({ ...userData, email: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md dark:bg-gray-700 dark:text-white"
              placeholder="marie.dupont@example.com"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Rôle
            </label>
            <select
              value={userData.role}
              onChange={(e) => setUserData({ ...userData, role: e.target.value as any })}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md dark:bg-gray-700 dark:text-white"
              required
            >
              <option value="enumerator">Enquêteur (Enumerator)</option>
              <option value="project_manager">Manager de Projet</option>
              <option value="supervisor">Superviseur</option>
              <option value="admin">Administrateur</option>
            </select>
          </div>
          {error && (
            <div className="text-red-600 dark:text-red-400 text-sm">{error}</div>
          )}
          <div className="flex space-x-3 mt-6">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 bg-gray-300 hover:bg-gray-400 text-gray-800 px-4 py-2 rounded-md dark:bg-gray-600 dark:text-white"
              disabled={isLoading}
            >
              Annuler
            </button>
            <button
              type="submit"
              disabled={isLoading}
              className="flex-1 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md disabled:opacity-50"
            >
              {isLoading ? 'Création...' : 'Créer Utilisateur'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default UserCreationModal;
